/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          black: "#000000",
          white: "#FFFFFF",
        },
        accent: {
          orange: "#F89C02",
        },
        neutral: {
          white: "#FFFFFF",
          gray: {
            600: "#E6E6E6",
            500: "#B0B0B0",
            400: "#555555",
          },
          black: "#000000",
        },
        bg: {
          primary: "#FFFFFF",
          secondary: "#F5F8FE",
          tertiary: "#CEE0F6",
        },
        vendor: {
          orange: "#F89E07",
          "orange-dark": "#E08F06",
          surface: "#FFFFFF",
          "surface-warm": "#FFFDFC",
          canvas: "#F3EEE7",
          border: "#EEEEEE",
          "text-primary": "#2D2D2D",
          "text-secondary": "#6B6B6B",
          "text-nav": "#534433",
          link: "#8C5A2B",
          success: "#1E8E3E",
          "success-bg": "#E6F4EA",
          neutral: "#4B5563",
          "neutral-bg": "#F3F4F6",
          "icon-bg": "#FFEDD5",
          "progress-bg": "#FEF3C7",
          "progress-text": "#B45309",
          "progress-featured-bg": "#FEF9C3",
          "progress-featured-text": "#854D0E",
          confirmed: "#8C5A2B",
          "confirmed-bg": "#F8E5CA",
          danger: "#C5221F",
          "danger-bg": "#FCE8E8",
          "nav-bar": "#FCEBDC",
        },
      },
      fontFamily: {
        display: ["Marcellus", "serif"],
        body: ["DM Sans", "sans-serif"],
        accent: ["Montserrat", "sans-serif"],
        vendor: ["Inter", "DM Sans", "sans-serif"],
        "vendor-display": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "vendor-accent": ["Montserrat", "Inter", "sans-serif"],
      },
      backgroundImage: {
        "gradient-blue": "linear-gradient(180deg, #F5F8FE 0%, #CEE0F6 100%)",
        "gradient-orange": "linear-gradient(135deg, #F89C02 0%, #FFB84D 100%)",
        "gradient-vendor": "linear-gradient(135deg, #F89E07 0%, #FFB84D 100%)",
      },
      boxShadow: {
        "vendor-card": "0px 4px 10px rgba(84, 62, 0, 0.25)",
        "vendor-card-lg": "0px 4px 10px rgba(84, 62, 0, 0.25)",
        "vendor-nav": "0px 4px 4px rgba(0, 0, 0, 0.25)",
      },
      fontSize: {
        "vendor-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.02em" }],
        "vendor-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em" }],
        "vendor-base": ["14px", { lineHeight: "20px" }],
        "vendor-lg": ["16px", { lineHeight: "24px" }],
        "vendor-xl": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em" }],
        "vendor-2xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em" }],
        "vendor-3xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em" }],
      },
      borderRadius: {
        vendor: "12px",
        "vendor-lg": "16px",
      },
      spacing: {
        "vendor-xs": "4px",
        "vendor-sm": "8px",
        "vendor-md": "12px",
        "vendor-lg": "16px",
        "vendor-xl": "20px",
        "vendor-2xl": "24px",
      },
    },
  },
  plugins: [],
};
