// Mock Users Data
export const mockUsers = [
  {
    id: 1,
    email: 'customer@example.com',
    password: 'password123',
    role: 'customer',
    name: 'John Doe',
    phone: '+1234567890',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  },
  {
    id: 2,
    email: 'salon@example.com',
    password: 'password123',
    role: 'salon',
    name: 'Jane Smith',
    phone: '+1234567891',
    salonId: 1,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
  },
  {
    id: 3,
    email: 'hmr@example.com',
    password: 'password123',
    role: 'hmr',
    name: 'Mike Johnson',
    phone: '+1234567892',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
  },
  {
    id: 4,
    email: 'admin@example.com',
    password: 'password123',
    role: 'admin',
    name: 'Admin User',
    phone: '+1234567893',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
  },
];

// Mock Salons Data
export const mockSalons = [
  {
    id: 1,
    name: 'Glamour Studio',
    owner: 'Jane Smith',
    ownerId: 2,
    email: 'glamour@salon.com',
    phone: '+1234567894',
    address: '123 Beauty St, New York, NY 10001',
    location: { lat: 40.7128, lng: -74.0060 },
    description: 'Premium salon offering hair styling, coloring, and spa services.',
    rating: 4.8,
    reviewCount: 124,
    images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800',
    ],
    status: 'approved',
    submittedBy: 3,
    submittedAt: '2025-01-15T10:30:00Z',
    approvedAt: '2025-01-16T14:20:00Z',
    categories: ['Hair', 'Spa', 'Nails'],
    workingHours: {
      monday: '9:00 AM - 8:00 PM',
      tuesday: '9:00 AM - 8:00 PM',
      wednesday: '9:00 AM - 8:00 PM',
      thursday: '9:00 AM - 8:00 PM',
      friday: '9:00 AM - 9:00 PM',
      saturday: '10:00 AM - 9:00 PM',
      sunday: '10:00 AM - 6:00 PM',
    },
  },
  {
    id: 2,
    name: 'Beauty Haven',
    owner: 'Sarah Williams',
    ownerId: 5,
    email: 'info@beautyhaven.com',
    phone: '+1234567895',
    address: '456 Style Ave, Los Angeles, CA 90001',
    location: { lat: 34.0522, lng: -118.2437 },
    description: 'Modern salon specializing in trendy cuts and creative color.',
    rating: 4.6,
    reviewCount: 89,
    images: [
      'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800',
    ],
    status: 'approved',
    submittedBy: 3,
    submittedAt: '2025-02-10T09:15:00Z',
    approvedAt: '2025-02-11T11:30:00Z',
    categories: ['Hair', 'Makeup'],
    workingHours: {
      monday: '10:00 AM - 7:00 PM',
      tuesday: '10:00 AM - 7:00 PM',
      wednesday: '10:00 AM - 7:00 PM',
      thursday: '10:00 AM - 7:00 PM',
      friday: '10:00 AM - 8:00 PM',
      saturday: '9:00 AM - 8:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 3,
    name: 'Elite Hair Lounge',
    owner: 'David Brown',
    ownerId: 6,
    email: 'contact@elitehair.com',
    phone: '+1234567896',
    address: '789 Elegance Blvd, Miami, FL 33101',
    location: { lat: 25.7617, lng: -80.1918 },
    description: 'Luxury hair salon with expert stylists and premium products.',
    rating: 4.9,
    reviewCount: 156,
    images: [
      'https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=800',
    ],
    status: 'pending',
    submittedBy: 3,
    submittedAt: '2025-10-20T14:45:00Z',
    categories: ['Hair', 'Treatments'],
    workingHours: {
      monday: '9:00 AM - 9:00 PM',
      tuesday: '9:00 AM - 9:00 PM',
      wednesday: '9:00 AM - 9:00 PM',
      thursday: '9:00 AM - 9:00 PM',
      friday: '9:00 AM - 10:00 PM',
      saturday: '8:00 AM - 10:00 PM',
      sunday: '10:00 AM - 7:00 PM',
    },
  },
];

// Mock Services Data
export const mockServices = [
  {
    id: 1,
    salonId: 1,
    name: 'Haircut & Styling',
    description: 'Professional haircut with expert styling',
    price: 50,
    duration: 60,
    category: 'Hair',
  },
  {
    id: 2,
    salonId: 1,
    name: 'Hair Coloring',
    description: 'Full hair coloring service with premium products',
    price: 120,
    duration: 120,
    category: 'Hair',
  },
  {
    id: 3,
    salonId: 1,
    name: 'Spa Facial',
    description: 'Relaxing facial treatment with skin analysis',
    price: 80,
    duration: 90,
    category: 'Spa',
  },
  {
    id: 4,
    salonId: 1,
    name: 'Manicure & Pedicure',
    description: 'Complete nail care with polish',
    price: 60,
    duration: 75,
    category: 'Nails',
  },
  {
    id: 5,
    salonId: 2,
    name: 'Balayage',
    description: 'Hand-painted highlighting technique',
    price: 180,
    duration: 180,
    category: 'Hair',
  },
  {
    id: 6,
    salonId: 2,
    name: 'Bridal Makeup',
    description: 'Professional makeup for your special day',
    price: 150,
    duration: 120,
    category: 'Makeup',
  },
];

// Mock Bookings Data
export const mockBookings = [
  {
    id: 1,
    customerId: 1,
    customerName: 'John Doe',
    salonId: 1,
    salonName: 'Glamour Studio',
    serviceId: 1,
    serviceName: 'Haircut & Styling',
    date: '2025-10-28',
    time: '10:00 AM',
    duration: 60,
    price: 50,
    status: 'confirmed',
    createdAt: '2025-10-22T08:30:00Z',
    notes: 'Please use organic products',
  },
  {
    id: 2,
    customerId: 1,
    customerName: 'John Doe',
    salonId: 1,
    salonName: 'Glamour Studio',
    serviceId: 2,
    serviceName: 'Hair Coloring',
    date: '2025-10-15',
    time: '2:00 PM',
    duration: 120,
    price: 120,
    status: 'completed',
    createdAt: '2025-10-10T11:20:00Z',
    notes: '',
  },
  {
    id: 3,
    customerId: 1,
    customerName: 'John Doe',
    salonId: 2,
    salonName: 'Beauty Haven',
    serviceId: 5,
    serviceName: 'Balayage',
    date: '2025-11-05',
    time: '11:00 AM',
    duration: 180,
    price: 180,
    status: 'pending',
    createdAt: '2025-10-23T15:45:00Z',
    notes: 'First time customer',
  },
];

// Mock HMR Submissions Data
export const mockHMRSubmissions = [
  {
    id: 1,
    hmrId: 3,
    hmrName: 'Mike Johnson',
    salonId: 1,
    salonName: 'Glamour Studio',
    status: 'approved',
    submittedAt: '2025-01-15T10:30:00Z',
    reviewedAt: '2025-01-16T14:20:00Z',
    reviewedBy: 'Admin User',
    comments: 'Excellent documentation. Approved.',
  },
  {
    id: 2,
    hmrId: 3,
    hmrName: 'Mike Johnson',
    salonId: 2,
    salonName: 'Beauty Haven',
    status: 'approved',
    submittedAt: '2024-02-10T09:15:00Z',
    reviewedAt: '2024-02-11T11:30:00Z',
    reviewedBy: 'Admin User',
    comments: 'All requirements met. Approved.',
  },
  {
    id: 3,
    hmrId: 3,
    hmrName: 'Mike Johnson',
    salonId: 3,
    salonName: 'Elite Hair Lounge',
    status: 'pending',
    submittedAt: '2024-10-20T14:45:00Z',
    reviewedAt: null,
    reviewedBy: null,
    comments: null,
  },
];

// Mock Analytics Data
export const mockAnalytics = {
  totalSalons: 50,
  totalCustomers: 1250,
  totalBookings: 3420,
  totalRevenue: 125000,
  pendingSalons: 5,
  activeHMRs: 12,
  monthlyBookings: [
    { month: 'Jan', bookings: 280 },
    { month: 'Feb', bookings: 320 },
    { month: 'Mar', bookings: 290 },
    { month: 'Apr', bookings: 350 },
    { month: 'May', bookings: 380 },
    { month: 'Jun', bookings: 420 },
    { month: 'Jul', bookings: 450 },
    { month: 'Aug', bookings: 410 },
    { month: 'Sep', bookings: 390 },
    { month: 'Oct', bookings: 430 },
  ],
  revenueByCategory: [
    { category: 'Hair', revenue: 65000 },
    { category: 'Spa', revenue: 28000 },
    { category: 'Nails', revenue: 18000 },
    { category: 'Makeup', revenue: 14000 },
  ],
  topSalons: [
    { name: 'Glamour Studio', bookings: 245, revenue: 12250 },
    { name: 'Beauty Haven', bookings: 198, revenue: 9900 },
    { name: 'Elite Hair Lounge', bookings: 187, revenue: 9350 },
  ],
};
