-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.booking_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  amount numeric NOT NULL,
  convenience_fee numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  razorpay_order_id character varying,
  razorpay_payment_id character varying,
  razorpay_signature character varying,
  payment_method character varying,
  failure_reason text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT booking_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_number character varying NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  salon_id uuid NOT NULL,
  service_id uuid NOT NULL,
  staff_id uuid,
  booking_date date NOT NULL,
  booking_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::booking_status CHECK (status = ANY (ARRAY['pending'::booking_status, 'confirmed'::booking_status, 'cancelled'::booking_status, 'completed'::booking_status, 'no_show'::booking_status])),
  service_price numeric NOT NULL,
  convenience_fee numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL,
  customer_name character varying NOT NULL,
  customer_phone character varying NOT NULL,
  customer_email character varying,
  special_requests text,
  confirmed_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT bookings_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.salon_staff(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES auth.users(id)
);
CREATE TABLE public.favorites (
  id bigint NOT NULL DEFAULT nextval('favorites_id_seq'::regclass),
  user_id uuid NOT NULL,
  salon_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT favorites_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name character varying NOT NULL,
  phone character varying,
  role USER-DEFINED NOT NULL DEFAULT 'customer'::user_role CHECK (role = ANY (ARRAY['admin'::user_role, 'relationship_manager'::user_role, 'vendor'::user_role, 'customer'::user_role])),
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  profile_image_url text,
  address text,
  city character varying,
  state character varying,
  pincode character varying,
  latitude numeric,
  longitude numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  salon_id uuid NOT NULL,
  staff_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  images jsonb,
  is_verified boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT reviews_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.salon_staff(id)
);
CREATE TABLE public.rm_profiles (
  id uuid NOT NULL,
  employee_id character varying NOT NULL UNIQUE,
  assigned_territories text[],
  performance_score integer DEFAULT 0,
  total_salons_added integer DEFAULT 0,
  total_approved_salons integer DEFAULT 0,
  joining_date date DEFAULT CURRENT_DATE,
  manager_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rm_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT rm_profiles_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.rm_profiles IS 'Relationship Manager specific data. User data (name, email, phone, is_active) stored in profiles table.';
CREATE TABLE public.rm_score_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rm_id uuid NOT NULL,
  salon_id uuid,
  score_change integer NOT NULL,
  reason text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rm_score_history_pkey PRIMARY KEY (id),
  CONSTRAINT rm_score_history_rm_id_fkey FOREIGN KEY (rm_id) REFERENCES public.rm_profiles(id),
  CONSTRAINT rm_score_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.salon_staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  salon_id uuid NOT NULL,
  user_id uuid,
  full_name character varying NOT NULL,
  email character varying,
  phone character varying NOT NULL,
  designation character varying,
  joining_date date DEFAULT CURRENT_DATE,
  is_active boolean DEFAULT true,
  specializations jsonb,
  profile_image_url text,
  bio text,
  average_rating numeric DEFAULT 0.0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT salon_staff_pkey PRIMARY KEY (id),
  CONSTRAINT salon_staff_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT salon_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.salons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid,
  rm_id uuid,
  join_request_id uuid,
  business_name character varying NOT NULL,
  business_type character varying NOT NULL,
  description text,
  phone character varying NOT NULL,
  email character varying,
  website character varying,
  address text NOT NULL,
  city character varying NOT NULL,
  state character varying NOT NULL,
  pincode character varying NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  gst_number character varying,
  business_license text,
  logo_url text,
  cover_image_url text,
  images jsonb,
  business_hours jsonb,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  average_rating numeric DEFAULT 0.0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  registration_fee_paid boolean DEFAULT false,
  registration_fee_amount numeric,
  registration_paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  subscription_status text DEFAULT 'pending'::text CHECK (subscription_status = ANY (ARRAY['pending'::text, 'active'::text, 'expired'::text, 'cancelled'::text])),
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  payment_amount numeric,
  payment_date timestamp with time zone,
  CONSTRAINT salons_pkey PRIMARY KEY (id),
  CONSTRAINT salons_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id),
  CONSTRAINT salons_rm_id_fkey FOREIGN KEY (rm_id) REFERENCES public.rm_profiles(id),
  CONSTRAINT salons_join_request_id_fkey FOREIGN KEY (join_request_id) REFERENCES public.vendor_join_requests(id)
);
CREATE TABLE public.service_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  icon_url text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  salon_id uuid NOT NULL,
  category_id uuid,
  name character varying NOT NULL,
  description text,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0::numeric),
  is_active boolean DEFAULT true,
  available_for_booking boolean DEFAULT true,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.staff_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_availability_pkey PRIMARY KEY (id),
  CONSTRAINT staff_availability_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.salon_staff(id)
);
CREATE TABLE public.system_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key character varying NOT NULL UNIQUE,
  config_value text NOT NULL,
  config_type character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_config_pkey PRIMARY KEY (id),
  CONSTRAINT system_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.token_blacklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token_jti character varying NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  token_type character varying NOT NULL CHECK (token_type::text = ANY (ARRAY['access'::character varying, 'refresh'::character varying]::text[])),
  blacklisted_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  reason character varying DEFAULT 'logout'::character varying,
  CONSTRAINT token_blacklist_pkey PRIMARY KEY (id),
  CONSTRAINT token_blacklist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  salon_id uuid,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_amount numeric DEFAULT 0,
  item_count integer DEFAULT 0,
  salon_name text,
  CONSTRAINT user_carts_pkey PRIMARY KEY (id),
  CONSTRAINT user_carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_join_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rm_id uuid NOT NULL,
  business_name character varying NOT NULL,
  business_type character varying NOT NULL,
  owner_name character varying NOT NULL,
  owner_email character varying NOT NULL,
  owner_phone character varying NOT NULL,
  business_address text NOT NULL,
  city character varying NOT NULL,
  state character varying NOT NULL,
  pincode character varying NOT NULL,
  latitude numeric,
  longitude numeric,
  gst_number character varying,
  business_license text,
  documents jsonb,
  status USER-DEFINED DEFAULT 'pending'::request_status CHECK (status = ANY (ARRAY['draft'::request_status, 'pending'::request_status, 'approved'::request_status, 'rejected'::request_status])),
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_join_requests_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_join_requests_rm_id_fkey FOREIGN KEY (rm_id) REFERENCES public.rm_profiles(id),
  CONSTRAINT vendor_join_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  salon_id uuid,
  payment_type USER-DEFINED NOT NULL CHECK (payment_type = ANY (ARRAY['registration_fee'::payment_type, 'convenience_fee'::payment_type, 'service_payment'::payment_type])),
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  razorpay_order_id character varying,
  razorpay_payment_id character varying,
  razorpay_signature character varying,
  payment_method character varying,
  failure_reason text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT vendor_payments_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payments_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id),
  CONSTRAINT vendor_payments_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);